### ISSUE TITLE
Errors working with material-ui version 0.16

### ISSUE THREAD

**Issue by kstratis** [ultimate-pagination/react-ultimate-pagination-material-ui#1]
When used with material-ui v0.16, npm complains about unmeet dependancies.

**Comment by dmytroyarmak** [comment]
Thanks @kstratis for the issue
The current version of this module requires `"material-ui": "^0.15.0"` as a peer dependency.
If `0.16` is backward compatible with `0.15` this peer dependency can be updated to `>0.15` without any other changes. Otherwise, usage of Material UI components needs to be updated together with `peerDependencies`. 
I don't have time to do it right now but I'll look at it asap (maybe even today evening). If you want, you can do it too 😄

**Comment by dmytroyarmak** [comment]
@kstratis it's fixed now in version `0.4.1`
